# Generated by Django 6.0.1 on 2026-01-09 15:18

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.get_profile_pic_path)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per hour in £', max_digits=6, null=True)),
                ('qts_certificate', models.FileField(blank=True, null=True, upload_to=accounts.models.get_file_path)),
                ('dbs_certificate', models.FileField(blank=True, null=True, upload_to=accounts.models.get_file_path)),
                ('documents_approved', models.BooleanField(default=False)),
                ('referee1_name', models.CharField(blank=True, max_length=200)),
                ('referee1_email', models.EmailField(blank=True, max_length=200)),
                ('referee2_name', models.CharField(blank=True, max_length=200)),
                ('referee2_email', models.EmailField(blank=True, max_length=200)),
                ('references_approved', models.BooleanField(default=False)),
                ('id_check_completed', models.BooleanField(default=False, verbose_name='ID Check Completed')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('subjects', models.ManyToManyField(blank=True, related_name='tutors', to='accounts.subject')),
                ('subject_levels', models.ManyToManyField(blank=True, related_name='tutors', to='accounts.subjectlevel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
